### ISSUE TITLE
pypi-package

### ISSUE THREAD

**Issue by bendikmaas** [Farama-Foundation/Procgen2#14]
Hi!

I'm having issues with installing and setting up this package manually. Can this be expected to be available as a pypi-package any time soon?

Thanks in advance for the response and the effort put into this project!

**Comment by 222464** [comment]
Hi,

The project isn't done yet, so only manual compilation for now, and therefore no pypi package yet, sorry!

We are still missing several games, which will be followed by packaging. We are looking for contributors to help add more games!
